apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  labels:
    app: nginx-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx
        image: ghcr.io/$GH_USERNAME/nginx-test:$IMAGE_VERSION
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: github-container-registry-secrets
